### ISSUE TITLE
Unable to get response from Rust commands

### ISSUE THREAD

**Issue by iamallama** [alexevladgabriel/php-webrcon#6]
First, thanks for this package. I tried several options and nothing worked at all.

Second, in the receive method, you are mapping over the response array and calling `json_decode` on each value (line 76). This is changing any part of the response to null if the text isn't numeric or JSON. For example, the "Type" index is always null when the text returned from the response should say "Generic".

As for the title, there are several Rust commands that don't return JSON, but just raw text. For example, the `stats` returns a list of all players connected and some stats about them (time, kills, deaths, etc). Any responses to those commands gets basically converted to null. So you basically can't use this class for rust commands without modification.

IMO, the message text should return the original text if a json_decode fails (returns null). I have personally modified the array map at lines 75-77 to...

```
        // decode the response
        $response = json_decode($this->client->receive(), true);
        // decode the message as json or the original text if json decode failed
        $response['Message'] = json_decode($response['Message']) ?? $response['Message'];
```

**Comment by alexevladgabriel** [comment]
Thanks for contributing @Limmek @iamallama & sorry for long delay, yesterday I had seen the issue for the first time.
